// seederQuiz.js

/**
 * Seeder file for inserting sample quizzes into MongoDB.
 * Language: English
 */

require('dotenv').config();
const mongoose = require('mongoose');
const Quiz = require('./models/Quiz');

// 1. Connect to MongoDB
mongoose
  .connect(process.env.MONGODB_URI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => {
    console.log('✅ MongoDB connected for quiz seeding');
    importQuizData();
  })
  .catch((err) => {
    console.error('❌ MongoDB connection error:', err.message);
    process.exit(1);
  });

// 2. Define sample quizzes (no need to provide slug—model hook will generate it)
const quizzes = [
  {
    title: 'Solar System Basics',
    level: 'basic',
    questions: [
      {
        question: 'Which planet is known as the Red Planet?',
        options: ['Earth', 'Mars', 'Jupiter', 'Venus'],
        correctAnswer: 'Mars',
      },
      {
        question: 'What is the largest planet in our solar system?',
        options: ['Saturn', 'Jupiter', 'Neptune', 'Earth'],
        correctAnswer: 'Jupiter',
      },
      {
        question: 'Which planet is closest to the Sun?',
        options: ['Mercury', 'Venus', 'Earth', 'Mars'],
        correctAnswer: 'Mercury',
      },
    ],
  },
  {
    title: 'Advanced Astronomy Quiz',
    level: 'advanced',
    questions: [
      {
        question: 'What is the approximate orbital period of Neptune?',
        options: ['165 years', '84 years', '248 years', '12 years'],
        correctAnswer: '165 years',
      },
      {
        question: 'Which moon is the largest in the solar system?',
        options: ['Titan', 'Ganymede', 'Callisto', 'Io'],
        correctAnswer: 'Ganymede',
      },
      {
        question: 'What is the common name for the asteroid belt region between Mars and Jupiter?',
        options: ['Kuiper Belt', 'Oort Cloud', 'Main Belt', 'Scattered Disc'],
        correctAnswer: 'Main Belt',
      },
    ],
  },
  {
    title: 'Planetary Composition',
    level: 'basic',
    questions: [
      {
        question: 'Which gas makes up most of Jupiter’s atmosphere?',
        options: ['Oxygen', 'Hydrogen', 'Carbon Dioxide', 'Nitrogen'],
        correctAnswer: 'Hydrogen',
      },
      {
        question: 'Which planet has a surface composed mostly of iron and nickel?',
        options: ['Mercury', 'Venus', 'Mars', 'Earth'],
        correctAnswer: 'Mercury',
      },
      {
        question: 'Which planet’s atmosphere is primarily carbon dioxide?',
        options: ['Mars', 'Venus', 'Earth', 'Saturn'],
        correctAnswer: 'Venus',
      },
    ],
  },
];

const importQuizData = async () => {
  try {
    // Remove existing quizzes
    await Quiz.deleteMany();
    console.log('🗑  Existing quizzes removed');

    // Insert sample quizzes (slug will be auto-generated by model hook)
    await Quiz.insertMany(quizzes);
    console.log('✅ Quiz data imported successfully');
    process.exit();
  } catch (error) {
    console.error('❌ Error importing quiz data:', error);
    process.exit(1);
  }
};
